services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app/src
      - ../bin:/app/bin
    restart: on-failure
    ports:
      - "8080:8000"
    depends_on:
      - db
    command: [ "./bin/wait-for-it.sh", "db:5432", "--", "uvicorn", "entrypoints.api:app", "--host", "0.0.0.0", "--reload" ]

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=books